In [7]:
import scipy
import torch
import finufft
import numpy as np

from numpy.random import standard_normal

In [12]:
Ns = [5, 10, 100, 1000, 100000]
case1 = np.array([1.0, 2.5, -1.0, -1.5, 1.5], dtype=np.complex128)
cases = [
    case1,
]

for i in Ns:
    cases.append(standard_normal(i) + 1j * standard_normal(i))

# cases

In [13]:
curr = cases[0]

curr

array([ 1. +0.j,  2.5+0.j, -1. +0.j, -1.5+0.j,  1.5+0.j])

In [14]:
curr_tensor = torch.from_numpy(curr)
against_torch = torch.fft.fft(curr_tensor)

In [19]:
N = len(curr)

finufft_out = finufft.nufft1d1(
    2 * np.pi * np.arange(0, 1, 1 / N), curr, N, modeord=1
)

In [20]:
against_torch

tensor([ 2.5000+0.0000j,  4.2586-1.2449j, -3.0086-0.1123j, -3.0086+0.1123j,
         4.2586+1.2449j], dtype=torch.complex128)

In [22]:
finufft_out

array([ 2.50000162+0.j        ,  4.25861085+1.24494905j,
       -3.00861111+0.11225689j, -3.00861111-0.11225689j,
        4.25861085-1.24494905j])

In [21]:
torch.norm(torch.from_numpy(finufft_out) - against_torch) / N

tensor(0.7071, dtype=torch.float64)